Swamis/Controllers/TradesController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script;
using System.Web.Script.Serialization;

using Sawtooth.GV_Entities;
using Sawtooth.Common;
using SawTooth.GV_Bus;

using System.Threading.Tasks;
using Sawtooth.Swamis.Controllers;
using Sawtooth.Swamis.Models;
using System.Net.Http;

namespace Swamis.Controllers
{
    public class TradesController : BaseController
    {
        // GET: Trades
        public ActionResult Index()
        {
            if (!userAuthorized())
            {
                return RedirectToAction("Login", "Account");
            }
            SearchModel model = new SearchModel();

            switch (DateTime.Today.DayOfWeek)
            {
                case DayOfWeek.Friday:
                    model.EndDate = DateTime.Today.AddDays(3);
                    break;
                case DayOfWeek.Saturday:
                    model.StartDate = DateTime.Today.AddDays(-1);
                    model.EndDate = DateTime.Today.AddDays(2);
                    break;
                case DayOfWeek.Sunday:
                    model.StartDate = DateTime.Today.AddDays(-2);
                    break;
                default:
                    model.StartDate = DateTime.Today;
                    model.EndDate = DateTime.Today.AddDays(1);
                    break;
            }

            List<DailyTradesModel> dailies = new List<DailyTradesModel>();
            dailies.Add(new DailyTradesModel { Symbol = StaticRoutines.GetSymbol("GC", DateTime.Today) });
            dailies.Add(new DailyTradesModel { Symbol = StaticRoutines.GetSymbol("SP", DateTime.Today) });
            dailies.Add(new DailyTradesModel { Symbol = StaticRoutines.GetSymbol("ZB", DateTime.Today) });
            model.DailyTradesModel = dailies;
            model.DoQuote = false;
            model.DoTrigger = false;
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(SearchModel model)
        {
            //TODO:  add notification to page
            StringBuilder sb = new StringBuilder();
            if (model.DoQuote)
            {
                try
                {
                    MongoEngine db = new MongoEngine();
                    Quoter qs = new Quoter();
                    foreach (DailyTradesModel mm in model.DailyTradesModel)
                    {
                        List<DailyTrades> tt = qs.GetBarchartHistory(model.StartDate, mm.Symbol);
                        DailyTrades dd = tt.FirstOrDefault(x => x.CloseDate == model.StartDate);
                        sb.AppendLine(string.Format("{0}: Open: {1}, Hi: {2}, Low: {3}, Close: {4}\n",
                            dd.Symbol, dd.OpenPrice.ToString(), dd.HiPrice.ToString(), dd.LowPrice.ToString(), dd.ClosePrice.ToString()));
                        db.UpdateTrade(dd);
                    }

                }
                catch (Exception exc)
                {
                    //MessageBox.Show("Error during quote retrieval: " + exc.Message);
                    string msg = exc.Message;
                    sb.AppendLine(exc.Message);
                    sb.AppendLine(exc.StackTrace);
                }

            }
            if(model.DoTrigger)
            {
                try
                {
                    Sawtooth.GV_Bus.BusBase bus = new Sawtooth.GV_Bus.BusBase();
                    List<PricePattern> pp = bus.ProcessTDWSymbol(model.DailyTradesModel[1].Symbol,
                        model.DailyTradesModel[2].Symbol,
                        model.DailyTradesModel[0].Symbol,
                        model.EndDate);
                    return RedirectToAction("ViewTriggers", "Triggers", new {tradeDate = model.EndDate});
                }
                catch (Exception exc)
                {
                    sb.AppendLine(exc.Message);
                    sb.AppendLine(exc.StackTrace);
                }
            }
            ViewBag.Message = sb.ToString();
            //return RedirectToAction("ViewTrades", new { startDate = model.StartDate, endDate = model.EndDate });
            return View(model);
        }

        public ActionResult ViewTrades(DateTime startDate, DateTime endDate)
        {
            if (!userAuthorized())
            {
                return RedirectToAction("Login", "Account");
            }
            SearchModel model = new SearchModel
            {
                StartDate = startDate,
                EndDate = endDate
            };

            string result = "";
            string path = ConfigurationManager.AppSettings["tradesSvc"];
            string action = "GetTradeByDates/" +
                startDate.ToString("yyyy-MM-dd") + "/" +
                endDate.ToString("yyyy-MM-dd");
            List<DailyTradesModel> trades = new List<DailyTradesModel>();
            using (WebClient wc = new WebClient())
            {
                result = wc.DownloadString(path + action);
                if (!string.IsNullOrWhiteSpace(result))
                {
                    trades = new JavaScriptSerializer().Deserialize<List<DailyTradesModel>>(result);
                }
            }
            foreach (DailyTradesModel dt in trades)
            {
                dt.CloseDate = dt.CloseDate.AddHours(AddOffSet());
                if (dt.Symbol.Contains("ZB"))
                {

                    dt.sClosePrice = StaticRoutines.DecTo32Display(dt.ClosePrice);
                    dt.sHiPrice = StaticRoutines.DecTo32Display(dt.HiPrice);
                    dt.sLowPrice = StaticRoutines.DecTo32Display(dt.LowPrice);
                    dt.sOpenPrice = StaticRoutines.DecTo32Display(dt.OpenPrice);
                }
                else
                {
                    dt.sClosePrice = dt.ClosePrice.ToString("0.00");
                    dt.sHiPrice = dt.HiPrice.ToString("0.00");
                    dt.sLowPrice = dt.LowPrice.ToString("0.00");
                    dt.sOpenPrice = dt.OpenPrice.ToString("0.00");
                }
            }
            model.DailyTradesModel = trades;
            return View(model);

        }

        [HttpPost]
        public ActionResult ViewTrades(SearchModel model)
        {
            return RedirectToAction("ViewTrades", new { startDate = model.StartDate, endDate = model.EndDate });
        }


        // GET: Trades/Details/5
        public ActionResult Details(string id)
        {
            if (!userAuthorized())
            {
                return RedirectToAction("Login", "Account");
            }
            string result = "";
            string path = ConfigurationManager.AppSettings["tradesSvc"];
            string action = "GetTrade/x/" + id;
            List<DailyTrades> trades = new List<DailyTrades>();
            using (WebClient wc = new WebClient())
            {
                result = wc.DownloadString(path + action);
                if (!string.IsNullOrWhiteSpace(result))
                {
                    trades = new JavaScriptSerializer().Deserialize<List<DailyTrades>>(result);
                }
            }
            return View(trades[1]);
        }

        // GET: Trades/Create
        public ActionResult Create()
        {
            if (!userAuthorized())
            {
                return RedirectToAction("Login", "Account");
            }
            //ViewBag.Symbols = GetSymbols();
            DailyTradesModel model = new DailyTradesModel();
            model.TradeSymbols = GetSymbols();
            switch (DateTime.Today.DayOfWeek)
            {
                case DayOfWeek.Sunday:
                    model.CloseDate = DateTime.Today.AddDays(-2);
                    break;
                case DayOfWeek.Saturday:
                    model.CloseDate = DateTime.Today.AddDays(-1);
                    break;
                default:
                    model.CloseDate = DateTime.Today;
                    break;
            }
            return View(model);
        }

        // POST: Trades/Create
        [HttpPost]
        public ActionResult Create(DailyTradesModel model)
        {
            try
            {
                string msg = ValidateTrade(model);
                if (msg == "")
                {
                    DailyTrades dt = new DailyTrades
                    {
                        CloseDate = model.CloseDate,
                        ClosePrice = model.ClosePrice,
                        HiPrice = model.HiPrice,
                        Id = model.Id,
                        LowPrice = model.LowPrice,
                        OpenPrice = model.OpenPrice,
                        Volume = model.Volume
                    };
                    dt.Symbol = model.Symbol;
                    if (model.Symbol == "ZB")
                    {
                        dt.ClosePrice = StaticRoutines.ThirtyTwoToDec(model.ClosePrice);
                        dt.HiPrice = StaticRoutines.ThirtyTwoToDec(model.HiPrice);
                        dt.LowPrice = StaticRoutines.ThirtyTwoToDec(model.LowPrice);
                        dt.OpenPrice = StaticRoutines.ThirtyTwoToDec(model.OpenPrice);
                    }
                    MongoEngine db = new MongoEngine();
                    List<DailyTrades> trades = new List<DailyTrades>();
                    trades = db.UpdateTrade(dt);
                    return View();
                }
                else
                {

                }

                return RedirectToAction("Create");
            }
            catch (Exception exc)
            {
                return View();
            }
        }

Swamis/Views/Trades/AutomatedQuote.cshtml
@{
    ViewBag.Title = "AutomatedQuote";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AutomatedQuote</h2>

Swamis/Views/Trades/Create.cshtml
@model Sawtooth.Swamis.Models.DailyTradesModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Trade</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.Symbol, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Symbol, new { @class = "form-control" })
            </div>
        </div>
       <div class="form-group">
            @Html.LabelFor(m => m.OpenPrice, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.OpenPrice, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.HiPrice, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.HiPrice, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.LowPrice, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.LowPrice, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ClosePrice, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.ClosePrice, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Volume, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Volume, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.CloseDate, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.CloseDate, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
}

Swamis/Views/Trades/Edit.cshtml
@model Sawtooth.Swamis.Models.DailyTradesModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TradeList</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.Id, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DisplayFor(m => m.Id)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Symbol, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.Symbol, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.OpenPrice, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.OpenPrice, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.HiPrice, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.HiPrice, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.LowPrice, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.LowPrice, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ClosePrice, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.ClosePrice, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Volume, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.Volume, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.CloseDate, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.CloseDate, new { @class = "form-control" })
            </div>
        </div>
        @Html.HiddenFor(m => m.Id)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Swamis/Views/Trades/Index.cshtml
@model Sawtooth.Swamis.Models.SearchModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>Trades Home</h2>
@using (Html.BeginForm("Index","Trades", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.DoQuote)
    @Html.HiddenFor(m => m.DoTrigger)

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @ViewBag.Message
        </div>
        <div class="form-group">
            @Html.Label("Quote Date", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.StartDate, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Signal Date", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.EndDate, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("GOLD", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.DailyTradesModel[0].Symbol, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("S & P", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.DailyTradesModel[1].Symbol, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("TREASURY", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.DailyTradesModel[2].Symbol, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a class="btn btn-default" id="quoteLink" href="#" onclick="quoteClick();">Get Quotes</a>
                <a class="btn btn-default" id="triggerLink" href="#" onclick="triggerClick();">Get Triggers</a>
                @Html.ActionLink("Create New", "Create", "TradesController", new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}



@section Scripts {

<script type="text/javascript">
    $(document).ready(function () {
        $('input[type=datetime]').datepicker({
            dateFormat: "dd/M/yy",
            changeMonth: true,
            changeYear: true,
            yearRange: "-60:+0"
        });

    });

    function quoteClick() {
        $("#DoQuote").val("True");
        $("#DoTrigger").val("False");
        $("form:last").submit();
    }
    function triggerClick() {
        $("#DoQuote").val("False");
        $("#DoTrigger").val("True");
        $("form:last").submit();
    }


</script>  
}

Swamis/Views/Trades/ViewTrades.cshtml
@model Sawtooth.Swamis.Models.SearchModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View Trades</h2>
<p>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(m => m.StartDate, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.StartDate, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.EndDate, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.EndDate, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="View Trades" class="btn btn-default" />
                    @Html.ActionLink("Create New", "Create", " TradesController", new { @class = "btn btn-default" })

                </div>
            </div>
        </div>
    }


</p>

<table class="table">
    <tr>
        <th>Date</th>
        <th>Symbol</th>
        <th>Open</th>
        <th>Hi</th>
        <th>Low</th>
        <th>Close</th>
        <th>Vol</th>
        <th>Id</th>
        <th></th>
    </tr>
    @if (Model.DailyTradesModel.Count > 0)
    {
        foreach (var dt in Model.DailyTradesModel)
        {
            <tr>
                <td>
                    @Html.DisplayFor(x => dt.CloseDate)
                </td>
                <td>
                    @Html.DisplayFor(x => dt.Symbol)
                </td>
                <td>
                    @Html.DisplayFor(x => dt.sOpenPrice)
                </td>
                <td>
                    @Html.DisplayFor(x => dt.sHiPrice)
                </td>
                <td>
                    @Html.DisplayFor(x => dt.sLowPrice)
                </td>
                <td>
                    @Html.DisplayFor(x => dt.sClosePrice)
                </td>
                <td>
                    @Html.DisplayFor(x => dt.Volume)
                </td>
                <td>
                    @Html.DisplayFor(x => dt.Id)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = dt.Id })
                </td>
            </tr>
        }
    }
</table>
<p>
    |
</p>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}